- hosts: test
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: kubernetes-manifest/Deployment.yaml
      dest: /root/
  - name: delete the previous kubernetes objects 
    command: kubectl delete -f /root/Deployment.yaml
  - name: Create a Deployment by reading the definition from a local file
    command: kubectl apply -f /root/Deployment.yaml
  - name: copy service file to kubernetes master
    copy:
      src: kubernetes-manifest/Service.yaml
      dest: /root/
  - name: delete the previous kubernetes objects 
    command: kubectl delete -f /root/Service.yaml
  - name: Create a Service by reading the definition from a local file
    command: kubectl apply -f /root/Service.yaml
      